# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#

# db/seeds.rb

genres_with_descriptions = [
  { genre_name: "Ação", description: "O gênero Ação se caracteriza por histórias com ritmo acelerado, foco em sequências de ação espetaculares e personagens que se envolvem em situações perigosas.  Com ênfase em adrenalina e suspense, ele geralmente apresenta violência física, perseguições, explosões e acrobacias.  O objetivo é proporcionar emoção ao público, com um desenvolvimento rápido da trama e cenários grandiosos.  Alguns subgêneros incluem filmes de artes marciais, filmes de guerra e thrillers de ação." },
  { genre_name: "Comedia", description: "A comédia é um gênero de entretenimento que visa provocar risos e humor. Seus elementos incluem situações engraçadas, personagens excêntricos, diálogos espirituosos, sarcasmo, ironia e situações embaraçosas. A comédia pode ser apresentada em diversas formas, como filmes, peças teatrais, programas de televisão, stand-up comedy e livros. O objetivo principal da comédia é proporcionar ao público momentos de alegria e descontração, muitas vezes explorando as falhas e as idiossincrasias da vida." },
  { genre_name: "Drama", description: "Drama é um gênero que explora emoções complexas, conflitos e temas sérios através de personagens e narrativas realistas. Ele aborda dilemas humanos, relacionamentos, perdas, triunfos e a busca por significado. O drama busca provocar a empatia, o pensamento crítico e o questionamento do mundo ao redor. O tom pode variar de trágico a esperançoso, mas sempre com um foco profundo na experiência humana." },
  { genre_name: "Horror", description: "O gênero horror visa provocar medo, apreensão e terror no público, explorando temas como morte, violência, o sobrenatural e o psicológico. Utiliza elementos como monstros, fantasmas, serial killers e ambientes assustadores para criar uma atmosfera de suspense e criar sustos repentinos. O horror pode ser psicológico, gótico, sobrenatural ou slasher, com o objetivo de desafiar as crenças e provocar uma experiência emocional intensa." },
  { genre_name: "Ficção Cientifica", description: "A Ficção Científica (FC) é um gênero literário que explora o impacto da ciência e tecnologia na sociedade. Seus cenários frequentemente se passam em mundos futuros, em outros planetas ou em realidades alternativas, explorando temas como viagens espaciais, inteligência artificial, robótica e a busca por vida extraterrestre. A FC pode ser tanto especulativa quanto realista, usando a ciência como base para construir histórias com temas como a ética, o poder e a natureza da humanidade." },
  { genre_name: "Suspense", description: "Suspense é um gênero literário e cinematográfico que se caracteriza pela criação de tensão e expectativa, mantendo o público em estado de incerteza e apreensão. O foco está em criar uma atmosfera de mistério e suspense, com pistas e informações vagamente reveladas, levando o leitor ou espectador a questionar o que vai acontecer em seguida. O clímax geralmente envolve uma resolução dramática que revela a verdade por trás do mistério." },
  { genre_name: "Terror", description: "Terror é um gênero que busca provocar medo e apreensão no público, explorando temas como morte, violência, o sobrenatural e o psicológico.  Utiliza suspense, atmosfera tensa, jumpscares e elementos de horror para criar uma experiência visceral e perturbadora. O objetivo é levar o público a um estado de desconforto e apreensão, explorando seus medos e ansiedades mais profundos." },
  { genre_name: "Máfia", description: "O gênero Mafia é caracterizado por histórias que exploram o mundo do crime organizado, com foco em gangues, máfias e seus membros. As narrativas geralmente se concentram em temas como poder, traição, lealdade, violência e a busca por ascensão social. Os personagens são frequentemente complexos e moralmente ambíguos, navegando em um mundo de regras e códigos próprios. O gênero explora a natureza humana e suas falhas, mostrando como a ganância e a busca por poder podem levar à destruição." },
  { genre_name: "Fantasia", description: "Fantasia é um gênero de ficção que se baseia em elementos mágicos, sobrenaturais e míticos. Ele explora mundos fictícios, criaturas e sistemas mágicos, muitas vezes com personagens heróicos e jornadas extraordinárias. A fantasia pode ser épica, com batalhas e romances, ou íntima, com foco em personagens e seus desafios internos. Os elementos mágicos podem ser fundamentais para a trama ou servir como pano de fundo para histórias de aventura, romance e drama." },
  { genre_name: "Animação", description: "Animação é uma forma de arte que cria a ilusão de movimento através de uma série de imagens fixas, que são apresentadas em rápida sucessão. Pode ser 2D, 3D ou stop-motion, e é usada em filmes, televisão, jogos e outras mídias. A animação permite contar histórias de forma única, explorar mundos fantásticos e criar personagens memoráveis. Ela pode ser usada para fins de entretenimento, educação ou propaganda.  A animação é uma forma de arte versátil e poderosa que continua a cativar o público em todo o mundo." },
  { genre_name: "Documentário", description: "Documentário é um gênero cinematográfico que explora temas reais, utilizando imagens, entrevistas e narrações para informar, educar e entreter o público. Abrange uma ampla gama de assuntos, desde eventos históricos e questões sociais até naturezas e culturas. O objetivo é apresentar uma visão imparcial e factual, embora algumas produções possam ter uma inclinação ideológica.  A qualidade de um documentário reside em sua capacidade de envolver o público com histórias cativantes, visuais impactantes e uma narrativa coesa." },
  { genre_name: "Romance", description: "O gênero de filmes de romance explora relacionamentos amorosos e suas complexidades, oferecendo histórias que capturam a essência do amor em suas diversas formas. Desde encontros apaixonados até conflitos emocionais, esses filmes frequentemente abordam temas como a busca pela felicidade, o sacrifício e a superação de obstáculos. Elementos como diálogos emocionais, trilhas sonoras românticas e cenários pitorescos ajudam a criar uma atmosfera envolvente, fazendo com que o público se identifique e emocione com os personagens e suas jornadas amorosas." },
  { genre_name: "Crime", description: "O gênero Crime explora crimes, seus mistérios e suas consequências. Ele geralmente apresenta detetives, policiais ou investigadores que tentam resolver crimes, revelando pistas, interrogando suspeitos e confrontando os culpados. \n\nO suspense e a intriga são elementos-chave, com o foco na investigação, na resolução do crime e na busca pela justiça. Subgêneros incluem policiais, thrillers psicológicos, noir e mistério." },
  { genre_name: "Faroeste", description: "O faroeste é um gênero cinematográfico que retrata a vida no Velho Oeste americano, geralmente no século XIX. O gênero é caracterizado por cowboys, pistoleiros, saloons, indígenas, bandidos, e confrontos épicos. Temas comuns incluem a conquista da fronteira, justiça, vingança, e o embate entre a civilização e a selvageria. O faroeste clássico é marcado por paisagens áridas, duelos, e um código de conduta próprio, exaltando a liberdade e a individualidade." },
  { genre_name: "Musical", description: "O musical é um gênero teatral que combina música, dança e diálogo, contando uma história e explorando emoções. Suas origens remontam a antigas tradições musicais, mas ganhou forma moderna no século XIX. A música, geralmente original, impulsiona a trama e desenvolve os personagens. O gênero abrange diversos estilos, desde o clássico e o jazz ao rock e o pop, e atrai audiências de todas as idades. A magia do musical reside na capacidade de unir arte, emoção e entretenimento, criando uma experiência única e memorável." },
  { genre_name: "Biografia", description: "A biografia é um gênero literário que narra a história da vida de uma pessoa real, incluindo suas experiências, relacionamentos, realizações e impacto no mundo. Abrange desde a infância e adolescência até a vida adulta, revelando suas características, motivações e trajetória. \n\nA biografia pode ser escrita em primeira pessoa, pelo próprio biografado, ou em terceira pessoa, por um autor externo. A veracidade dos fatos é fundamental, mas o autor tem liberdade para interpretar e apresentar a história de acordo com seu ponto de vista. \n\nO objetivo é oferecer um retrato completo e autêntico do indivíduo, proporcionando ao leitor uma compreensão profunda de sua vida e legado." },
  { genre_name: "Policial", description: "O gênero policial, também conhecido como \"noir\", se caracteriza por histórias de crimes e mistérios, com foco na investigação. Detetives, muitas vezes cínicos e com métodos não convencionais, desvendam crimes complexos, enfrentando corrupção, violência e dilemas morais. Ambientado em cidades escuras e perigosas, o gênero explora a natureza humana, a justiça e a busca pela verdade. Personagens icônicos como Sherlock Holmes e Hercule Poirot personificam o gênero, que se adapta a diferentes formatos, do romance ao cinema e séries de TV." },
  { genre_name: "Guerra", description: "O gênero Guerra explora conflitos armados, focando em batalhas, táticas militares, consequências sociais e impacto psicológico. Pode apresentar histórias épicas de grandes conflitos, dramas pessoais de soldados, ou analisar a política e a ideologia por trás da guerra. O gênero explora temas como heroísmo, sacrifício, camaradagem, trauma, moralidade e a natureza humana." },
  { genre_name: "Artes Marciais", description: "Filmes de artes marciais destacam técnicas de combate e disciplina, combinando ação coreografada com filosofia e cultura. Com origem em tradições asiáticas como kung fu, karatê e jiu-jitsu, essas histórias enfatizam a superação pessoal, honra e autodefesa. Além de lutas emocionantes, o gênero explora o equilíbrio entre mente e corpo, tornando-se uma metáfora para o crescimento pessoal e espiritual." },
  { genre_name: "Aventura", description: "O gênero Aventura se caracteriza por narrativas que acompanham protagonistas em jornadas emocionantes e desafiadoras, geralmente envolvendo elementos de exploração, mistério, ação e superação de obstáculos. O foco está na viagem, nos desafios enfrentados e na transformação do herói.  Pode se passar em cenários históricos, futuristas, mágicos ou contemporâneos." },
  { genre_name: "Espionagem", description: "Espionagem é um gênero de ficção que gira em torno de espiões, indivíduos que secretamente coletam informações para governos ou organizações. As tramas geralmente envolvem intrigas internacionais, missões perigosas, traições, perseguições, e a busca por segredos importantes. O gênero explora temas como lealdade, moralidade, e as linhas tênues entre o certo e o errado, enquanto os personagens enfrentam dilemas éticos e se movem em um mundo de subterfúgios e mistérios." },
  { genre_name: "Thriller", description: "Thriller é um gênero literário e cinematográfico que se caracteriza por suspense, tensão e medo psicológico.  As histórias geralmente giram em torno de um protagonista que enfrenta uma ameaça iminente, seja um assassino em série, uma conspiração política ou um evento sobrenatural.  O foco está na criação de suspense gradual, culminando em um clímax emocionante e imprevisível.  O gênero explora temas como medo, paranoia e a luta pela sobrevivência." },
  { genre_name: "Mistério", description: "O gênero Mistério se caracteriza por apresentar um crime ou enigma que precisa ser solucionado. O foco está na investigação, geralmente conduzida por um detetive perspicaz, que reúne pistas, analisa evidências e desvenda a verdade por trás do crime. A trama é construída com suspense, reviravoltas e pistas falsas, culminando em uma resolução surpreendente e satisfatória. O mistério pode explorar temas como justiça, moralidade e a natureza humana." },
  { genre_name: "Dança", description: "Filmes de dança destacam o poder da expressão corporal através de coreografias envolventes e emocionantes. O enredo geralmente envolve superação pessoal, competições ou a busca de um sonho, onde a dança é o principal meio de transformação dos personagens. Esses filmes celebram a música, a arte e a paixão pelo movimento, com estilos que variam do balé ao hip-hop, combinando drama, romance e inspiração." },
  { genre_name: "Humor", description: "O gênero Humor se caracteriza pelo objetivo de provocar risadas e divertimento no público, geralmente utilizando ironia, sarcasmo, exagero, situações engraçadas e personagens excêntricos. Pode ser encontrado em diversas formas, como piadas, comédia stand-up, filmes, livros, séries e até mesmo no dia a dia. O humor pode ser usado para criticar, satirizar, aliviar tensões ou simplesmente para fazer as pessoas sorrirem." }
]

genres_with_descriptions.each do |genre|
  GenreDescription.find_or_create_by(genre_name: genre[:genre_name]) do |g|
    g.description = genre[:description]
  end
end
